---

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - assert:
        that: ansible_distribution == 'MacOSX'

    - import_role:
        name: _base
    - import_role:
        name: personal
    - import_role:
        name: dev

