---

target_defaults: []
  # - domain: org.macosforge.xquartz.X11
  #   key: enable_iglx
  #   type: bool
  #   value: true


target_casks:
  - iterm2
  - visual-studio-code
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - qlimagesize
  - quicklookase
  - qlvideo
  - webpquicklook
