---

target_defaults:
  - domain: .GlobalPreferences
    key: com.apple.mouse.scaling
    type: string
    value: -1

  - domain: .GlobalPreferences
    key: com.apple.scrollwheel.scaling
    type: string
    value: -1

  - domain: com.apple.TextEdit
    key: TabWidth
    type: string
    value: 4


target_dirs:
  - "{{ _xdg_conf_home_ }}"
  - "{{ _xdg_cache_home_ }}"
  - "{{ _launchd_home_ }}"
  - "{{ _scripts_bin_ }}"


target_links:
  - src: "~/Library/Mobile Documents/com~apple~CloudDocs"
    dest: "~/.icloud"


git_repos:
  - src: "https://github.com/cyproterone/iterm2.git"
    dest: "{{ _xdg_conf_home_ }}/iterm2"

  - src: "https://github.com/cyproterone/alacritty.git"
    dest: "{{ _xdg_conf_home_ }}/alacritty"
